import React from "react";
import { Hammer } from "lucide-react";
import {
  SwingIcon,
  StairsIcon,
  GrillIcon,
  ShutterIcon,
  DomeIcon,
} from "@/components/Icons";

export const products = [
  {
    id: "jula-1",
    name: "ડિઝાઈનર ઝુલા - ૧",
    description: "આકર્ષક અને મજબૂત ડિઝાઈનર ઝુલા",
    image: "/asset/jula/jula1.png",
    category: "ઝુલા",
  },
  {
    id: "jula-2",
    name: "ડિઝાઈનર ઝુલા - ૨",
    description: "આધુનિક સ્ટાઇલ ઝુલા",
    image: "/asset/jula/jula2.png",
    category: "ઝુલા",
  },
  {
    id: "jula-3",
    name: "ડિઝાઈનર ઝુલા - ૩",
    description: "પ્રીમિયમ ફેબ્રિકેશન ઝુલા",
    image: "/asset/jula/jula3.png",
    category: "ઝુલા",
  },
  {
    id: "jula-4",
    name: "ડિઝાઈનર ઝુલા - ૪",
    description: "લક્ઝુરિયસ હોમ ઝુલા",
    image: "/asset/jula/jula4.png",
    category: "ઝુલા",
  },
  {
    id: "jula-5",
    name: "ડિઝાઈનર ઝુલા - ૫",
    description: "સ્ટાઇલિશ ગાર્ડન ઝુલા",
    image: "/asset/jula/jula5.png",
    category: "ઝુલા",
  },
  {
    id: "jula-6",
    name: "ડિઝાઈનર ઝુલા - ૬",
    description: "મજબૂત આઉટડોર ઝુલા",
    image: "/asset/jula/jula6.png",
    category: "ઝુલા",
  },
  {
    id: "jula-7",
    name: "ડિઝાઈનર ઝુલા - ૭",
    description: "ક્લાસિક ઇન્ડોર ઝુલા",
    image: "/asset/jula/jula7.png",
    category: "ઝુલા",
  },
  {
    id: "dadar-1",
    name: "દાદર ડિઝાઇન - ૧",
    description: "મજબૂત અને ટકાઉ લોખંડના દાદર",
    image: "/asset/dadar/dadar1.png",
    category: "દાદર",
  },
  {
    id: "dadar-2",
    name: "દાદર ડિઝાઇન - ૨",
    description: "આધુનિક સ્ટાઇલ દાદર",
    image: "/asset/dadar/dadar2.jpg",
    category: "દાદર",
  },
  {
    id: "dadar-3",
    name: "દાદર ડિઝાઇન - ૩",
    description: "પ્રીમિયમ ફેબ્રિકેશન દાદર",
    image: "/asset/dadar/dadar3.jpg",
    category: "દાદર",
  },
  {
    id: "dadar-4",
    name: "દાદર ડિઝાઇન - ૪",
    description: "મજબૂત આઉટડોર દાદર",
    image: "/asset/dadar/dadar4.jpg",
    category: "દાદર",
  },
  {
    id: "dadar-5",
    name: "દાદર ડિઝાઇન - ૫",
    description: "સ્ટાઇલિશ ઇન્ડોર દાદર",
    image: "/asset/dadar/dadar5.jpg",
    category: "દાદર",
  },
  {
    id: "dadar-6",
    name: "દાદર ડિઝાઇન - ૬",
    description: "કસ્ટમ મેડ દાદર",
    image: "/asset/dadar/dadar6.jpg",
    category: "દાદર",
  },
  {
    id: "dadar-7",
    name: "દાદર ડિઝાઇન - ૭",
    description: "હેવી ડ્યુટી દાદર",
    image: "/asset/dadar/dadar7.jpg",
    category: "દાદર",
  },
  {
    id: "dadar-8",
    name: "દાદર ડિઝાઇન - ૮",
    description: "આકર્ષક દાદર ડિઝાઇન",
    image: "/asset/dadar/dadar8.jpg",
    category: "દાદર",
  },
  {
    id: "grill-1",
    name: "સેફ્ટી ગ્રીલ - ૧",
    description: "બારી અને દરવાજા માટે મજબૂત ગ્રીલ",
    image: "/asset/grill/grill/grill1.jpg",
    category: "ગ્રીલ અને સેફ્ટીડોર",
  },
  {
    id: "grill-2",
    name: "સેફ્ટી ગ્રીલ - ૨",
    description: "આધુનિક ડિઝાઇન ગ્રીલ",
    image: "/asset/grill/grill/grill2.jpg",
    category: "ગ્રીલ અને સેફ્ટીડોર",
  },
  {
    id: "grill-3",
    name: "સેફ્ટી ગ્રીલ - ૩",
    description: "મજબૂત લોખંડની ગ્રીલ",
    image: "/asset/grill/grill/grill3.jpg",
    category: "ગ્રીલ અને સેફ્ટીડોર",
  },
  {
    id: "grill-4",
    name: "સેફ્ટી ગ્રીલ - ૪",
    description: "પ્રીમિયમ સેફ્ટી ગ્રીલ",
    image: "/asset/grill/grill/grill4.jpg",
    category: "ગ્રીલ અને સેફ્ટીડોર",
  },
  {
    id: "grill-5",
    name: "સેફ્ટી ગ્રીલ - ૫",
    description: "સ્ટાઇલિશ વિન્ડો ગ્રીલ",
    image: "/asset/grill/grill/grill5.jpg",
    category: "ગ્રીલ અને સેફ્ટીડોર",
  },
  {
    id: "grill-6",
    name: "સેફ્ટી ગ્રીલ - ૬",
    description: "ડિઝાઈનર સેફ્ટી ગ્રીલ",
    image: "/asset/grill/grill/grill6.jpg",
    category: "ગ્રીલ અને સેફ્ટીડોર",
  },
  {
    id: "door-1",
    name: "સેફ્ટી ડોર - ૧",
    description: "મજબૂત સેફ્ટી દરવાજા",
    image: "/asset/grill/safetydoor/door1.jpg",
    category: "ગ્રીલ અને સેફ્ટીડોર",
  },
  {
    id: "door-2",
    name: "સેફ્ટી ડોર - ૨",
    description: "આધુનિક સેફ્ટી ડોર",
    image: "/asset/grill/safetydoor/door2.jpg",
    category: "ગ્રીલ અને સેફ્ટીડોર",
  },
  {
    id: "door-3",
    name: "સેફ્ટી ડોર - ૩",
    description: "ડિઝાઈનર સેફ્ટી ડોર",
    image: "/asset/grill/safetydoor/door3.jpg",
    category: "ગ્રીલ અને સેફ્ટીડોર",
  },
  {
    id: "door-4",
    name: "સેફ્ટી ડોર - ૪",
    description: "પ્રીમિયમ સેફ્ટી દરવાજા",
    image: "/asset/grill/safetydoor/door4.jpg",
    category: "ગ્રીલ અને સેફ્ટીડોર",
  },
  {
    id: "door-5",
    name: "સેફ્ટી ડોર - ૫",
    description: "મજબૂત લોખંડના દરવાજા",
    image: "/asset/grill/safetydoor/door5.jpg",
    category: "ગ્રીલ અને સેફ્ટીડોર",
  },
  {
    id: "door-6",
    name: "સેફ્ટી ડોર - ૬",
    description: "સ્ટાઇલિશ સેફ્ટી ડોર",
    image: "/asset/grill/safetydoor/door6.jpg",
    category: "ગ્રીલ અને સેફ્ટીડોર",
  },
  {
    id: "door-7",
    name: "સેફ્ટી ડોર - ૭",
    description: "હેવી ડ્યુટી સેફ્ટી ડોર",
    image: "/asset/grill/safetydoor/door7.jpg",
    category: "ગ્રીલ અને સેફ્ટીડોર",
  },
  {
    id: "door-8",
    name: "સેફ્ટી ડોર - ૮",
    description: "કસ્ટમ સેફ્ટી ડોર",
    image: "/asset/grill/safetydoor/door8.jpg",
    category: "ગ્રીલ અને સેફ્ટીડોર",
  },
  {
    id: "door-9",
    name: "સેફ્ટી ડોર - ૯",
    description: "આકર્ષક સેફ્ટી દરવાજા",
    image: "/asset/grill/safetydoor/door9.jpg",
    category: "ગ્રીલ અને સેફ્ટીડોર",
  },
  {
    id: "reling-1",
    name: "રેલિંગ ડિઝાઇન - ૧",
    description: "મજબૂત અને સ્ટાઇલિશ રેલિંગ",
    image: "/asset/reling/reling1.jpg",
    category: "રેલિંગ",
  },
  {
    id: "reling-2",
    name: "રેલિંગ ડિઝાઇન - ૨",
    description: "આધુનિક સ્ટેરકેસ રેલિંગ",
    image: "/asset/reling/reling2.jpg",
    category: "રેલિંગ",
  },
  {
    id: "reling-3",
    name: "રેલિંગ ડિઝાઇન - ૩",
    description: "ડિઝાઈનર બાલકની રેલિંગ",
    image: "/asset/reling/reling3.jpg",
    category: "રેલિંગ",
  },
  {
    id: "reling-4",
    name: "રેલિંગ ડિઝાઇન - ૪",
    description: "પ્રીમિયમ રેલિંગ ડિઝાઇન",
    image: "/asset/reling/reling4.jpg",
    category: "રેલિંગ",
  },
  {
    id: "reling-5",
    name: "રેલિંગ ડિઝાઇન - ૫",
    description: "હેવી ડ્યુટી રેલિંગ",
    image: "/asset/reling/reling5.jpg",
    category: "રેલિંગ",
  },
];

export const services = [
  {
    title: "ઝુલા",
    desc: "આધુનિક અને લક્ઝુરિયસ ઝુલા",
    icon: React.createElement(SwingIcon, { className: "text-[#C5A059]" }),
  },
  {
    title: "દાદર",
    desc: "મજબૂત અને ટકાઉ લોખંડના દાદર",
    icon: React.createElement(StairsIcon, { className: "text-[#C5A059]" }),
  },
  {
    title: "ગ્રીલ અને સેફ્ટીડોર",
    desc: "સેફ્ટી અને ક્લાસિક ડિઝાઇન",
    icon: React.createElement(GrillIcon, { className: "text-[#C5A059]" }),
  },
  {
    title: "રેલિંગ",
    desc: "આધુનિક અને સ્ટાઇલિશ રેલિંગ",
    icon: React.createElement(Hammer, { className: "text-[#C5A059]" }),
  },
  {
    title: "રોલિંગ શટર",
    desc: "મજબૂત અને ટકાઉ રોલિંગ શટર",
    icon: React.createElement(ShutterIcon, { className: "text-[#C5A059]" }),
  },
  {
    title: "ડોમ સ્ટ્રક્ચર",
    desc: "વોટરપ્રૂફ અને આકર્ષક શેડ્સ",
    icon: React.createElement(DomeIcon, { className: "text-[#C5A059]" }),
  },
];

export const navLinks = [
  { name: "સેવાઓ", href: "#services" },
  { name: "ગેલેરી", href: "#gallery" },
  { name: "સંપર્ક", href: "#contact" },
];

export const contactInfo = {
  phone: "9408207838",
  whatsapp: "9408207838",
  address: "શહેર ફરતી સડક, ભરતનગર, ભાવનગર",
  owners: [
    "ધીરુભાઈ જે. સિધ્ધપુરા  (મોરચંદવાળા)",
    "મિતેશભાઈ ડી. સિધ્ધપુરા",
    "હિરેનભાઈ ડી. સિધ્ધપુરા",
  ],
};
